name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          python -m pip install --user pipx
          python -m pipx ensurepath
          pipx install poetry==1.8.4

      - name: Install dependencies
        run: |
          poetry install --with build
          poetry run pre-commit install

      - name: Run pre-commit
        run: |
          poetry run pre-commit run --all-files

      - name: Run tests
        run: |
          poetry run pytest tests -v
