name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit pytest requests-mock
          pre-commit install
          pip install -r requirements.txt
      - name: Run pre-commit
        run: |
          pre-commit run --all-files
      - name: Run tests
        run: |
          pytest tests -v
